Repository paulscottrobson/neo6502-firmware, pull requests merged in 2024-02, with the labels that each got.

#61 Add a basic set of file I/O primitives.
  emulator/src/core/hardware.cpp
  firmware/common/config/dispatch.config
  firmware/common/include/data/dispatch_code.h
  firmware/common/include/interface/dispatch.h
  firmware/common/include/interface/filesystem.h
  firmware/common/sources/interface/dispatch.cpp
  firmware/common/sources/interface/fileinterface.cpp
  firmware/sources/hardware/fileimplementation.cpp
Labels: enhancement

#111 Add error handling to gitpython describe.
  firmware/common/scripts/prompt.py
Labels: enhancement

#102 Enable parallel builds.
  Makefile
  basic/Makefile
  emulator/Makefile
  emulator/javascript/Makefile
  firmware/Makefile
  firmware/common/Makefile
  kernel/Makefile
Labels: enhancement

#180 Fix make linux / windows on clean repo.
  Makefile
Labels: bug

#101 WIP - documentation: generate API documentation programmatically
  .github/workflows/build.yml
  .github/workflows/release.yml
  Makefile
  documents/api.texi
  documents/api.texi.in
Labels: documentation, enhancement, suggestions welcome
